backend:
  name: git-gateway
  branch: master
  
media_folder: "media"

collections:
  - name: "pages"
    label: "Pages"
    label_singular: "Page"
    folder: "/"
    create: true
    fields:
      - {label: "Title", name: "title", widget: "string", tagname: "h1"}
      - {label: "Image", name: "image", widget: "image", required: false}
      - {label: "Body", name: "body", widget: "markdown"}
